#AllCops:
  #TargetRubyVersion: 2.2

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
